src/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('love/', include('love.urls')),

    # API
    path('api/movies/', include('movies.api.urls'))
]

src/love/urls.py
from django.urls import path

from . import views
app_name = "love"
urlpatterns = [
    path('', views.ind, name="ind"),
    path('val', views.valnt, name='val'),
]

src/movies/api/urls.py
from django.urls import path
from movies.api.views import MovieCreateView, MovieListView

app_name = 'api_movies'

urlpatterns = [
    path('lst', MovieListView.as_view(), name='movies'),
    path('create', MovieCreateView.as_view(), name='create')
]

src/movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'

src/love/models.py
from django.db import models

# Create your models here.

src/movies/models.py
import uuid
from django.db import models

from .utils import make_uuid

# Create your models here.
class Person(models.Model):
    uuid = models.UUIDField(default=make_uuid)
    first_name = models.CharField(max_length=268)
    last_name = models.CharField(max_length=268, blank=True, null=True)
    birthdate = models.DateTimeField(blank=True, null=True)
    bio = models.TextField(blank=True, null=True)


    @property
    def names(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Country(models.Model):
    uuid = models.UUIDField(default=make_uuid)
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Genre(models.Model):
    uuid = models.UUIDField(default=make_uuid)
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Movie(models.Model):
    uuid = models.UUIDField(default=make_uuid)
    name_rus = models.CharField(max_length=256)
    name_orig = models.CharField(max_length=256)
    year = models.PositiveIntegerField()
    image = models.URLField()
    rating = models.DecimalField(blank=True, null=True, decimal_places=1, max_digits=3)
    country = models.ManyToManyField(to=Country)
    actors = models.ManyToManyField(to=Person, related_name='actors')
    director = models.ManyToManyField(to=Person, related_name='director')
    genre = models.ManyToManyField(to=Genre)

    def serialize(self):
        return {
            'id': self.uuid,
            'movieTitleOrig': self.name_orig,
            'movieTitleRus': self.name_rus,
            'country': self.country.all(),
            'movieActors': self.actors.all(),
            'director': self.director,
            'movieRate': self.rating,
            'year': self.year,
            'genre': self.genre.all(),
            'movieImageUrl': self.image,
        }

src/love/views.py
from random import choice
from django.shortcuts import render

# Create your views here.


def ind(request):
    return render(request, 'love/index.html')


def valnt(request):
    var_text = [
        'Пафдравляю тебя, ф днем свитова валимпина! Ула! Очень люблю тебя!',
        "Поздравляю тебя, Зайка моя, с празником! Ты самая хорошая и самая лучшая! Всегда будь такой милашкой!",
        "Поздравляю, Поздравляю, Поздравляю! Ура Ура Ура!",
        "С празником! Таичка-Заичка"
    ]
    pic_urls = [
        "http://www.mcgilltribune.com/wp-content/uploads/2019/02/Untitled-drawing-1-700x500.png",
        "https://catholic-sf.org/pictures/2020/2/Valentines_Day_Credit_MarjanCermelj__Shutterstock-1.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ05IY57AtM07F-lYuGtdQd4ihrnMcKpaIDHA&usqp=CAU",
        "https://c.files.bbci.co.uk/E10C/production/_105621675_gettyimages-1125351857.jpg",

    ]
    text = choice(var_text)
    img = choice(pic_urls)
    return render(request, 'love/val.html', {
        'text': text,
        'img': img,
    })

src/movies/api/views.py
from rest_framework import generics

from movies.api.serializers import MovieSerializer
from movies.models import Movie

class MovieListView(generics.ListAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class MovieCreateView(generics.ListCreateAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer
    

src/movies/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

src/love/templates/love/index.html
{% extends 'love/layout.html' %}

{% block title %}Love{% endblock %}

{% block body %}
<div class="card text-center">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Привет, Паичка. С праздником!</h5>
    <p class="card-text">Я не купил валентинку, и думаю, что это будет даже поприкольней, что я сделаю для тебя сам!
    Калочи, тут такое дело - за кнопафкой спьятано фто-та!</p>
    <a href="{% url 'love:val' %}" class="btn btn-primary">Пафматйеть фто там!</a>
  </div>
  <div class="card-footer text-muted">
    От Аефки!
  </div>
</div>
{% endblock %}

src/love/templates/love/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

src/love/templates/love/val.html
{% extends 'love/layout.html' %}

{% block title%}val{% endblock %}

{% block body %}
<div class="card" style="width: 18rem;">
  <img src={{img}} class="card-img-top" >
  <div class="card-body">
    <p class="card-text">{{text}}</p>
  </div>
</div>
{% endblock %}